import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (file: string) => readFileSync(resolve(process.cwd(), file), 'utf8')

describe('archive design tokens', () => {
  const theme = read('src/theme.css')
  const base = read('src/styles/base.css')
  const content = read('src/styles/content.css')
  const shell = read('src/styles/shell.css')
  const media = read('src/styles/media.css')
  const works = read('src/styles/works.css')
  const responsive = read('src/styles/responsive.css')

  it('defines the archive typography and layout scale', () => {
    expect(theme).toContain('--type-body-size: 1rem')
    expect(theme).toContain('--type-body-leading: 1.78')
    expect(theme).toContain('--type-secondary-size: .8125rem')
    expect(theme).toContain('--type-meta-size: .75rem')
    expect(theme).toContain('--font-prose: "Inter Variable", "Noto Sans SC Variable", sans-serif')
    expect(theme).toContain('--font-editorial: "Inter Variable", "Noto Serif SC Variable", serif')
    expect(theme).toContain('--font-technical: "IBM Plex Mono", "Noto Sans SC Variable", monospace')
    expect(theme).toContain('--tracking-latin-meta: .14em')
    expect(theme).toContain('--tracking-latin-wide: .18em')
    expect(theme).toContain('--tracking-zh-meta: .06em')
    expect(theme).toContain('--tracking-editorial: -.01em')
    expect(theme).toContain('--w-editorial: 700px')
    expect(theme).toContain('--w-data: 840px')
    expect(theme).toContain('--space-1: 4px')
    expect(theme).toContain('--space-2: 8px')
    expect(theme).toContain('--space-3: 12px')
    expect(theme).toContain('--space-4: 16px')
    expect(theme).toContain('--space-5: 24px')
    expect(theme).toContain('--space-6: 32px')
    expect(theme).toContain('--space-7: 48px')
    expect(theme).toContain('--space-8: 64px')
    expect(theme).toContain('--space-9: 96px')
    expect(theme).toContain('--space-10: 128px')
    expect(theme).toContain('--radius-small: 6px')
    expect(theme).toContain('--radius-card: 14px')
    expect(theme).toContain('--radius-large: 20px')
    expect(theme).toContain('--radius-pill: 999px')
  })

  it('keeps the public aliases and motion tokens on the semantic layer', () => {
    expect(theme).toContain('--sans: var(--font-prose)')
    expect(theme).toContain('--display: var(--font-editorial)')
    expect(theme).toContain('--mono: var(--font-technical)')
    expect(theme).toContain('--text-xs: var(--type-meta-size)')
    expect(theme).toContain('--text-sm: var(--type-secondary-size)')
    expect(theme).toContain('--w-read: var(--w-editorial)')
    expect(theme).toContain('--dur-micro:')
    expect(theme).toContain('--dur-fast:')
    expect(theme).toContain('--dur-base:')
    expect(theme).toContain('--dur-slow:')
    expect(theme).toContain('--dur-page:')
  })

  it('applies the semantic typography and width contract in the touched stylesheets', () => {
    expect(base).toContain('font-family: var(--font-prose)')
    expect(base).toContain('font-size: var(--type-body-size)')
    expect(base).toContain('line-height: var(--type-body-leading)')
    expect(content).toContain('font-family: var(--font-editorial)')
    expect(content).toContain('font-family: var(--font-technical)')
    expect(content).toContain('max-width: var(--w-editorial)')
    expect(content).toContain('max-width: var(--w-data)')
    expect(shell).toContain('font-family: var(--font-editorial)')
    expect(shell).toContain('font-family: var(--font-technical)')
    expect(shell).toContain('max-width: var(--w-editorial)')
    expect(media).toContain('font-family: var(--font-editorial)')
    expect(media).toContain('font-family: var(--font-technical)')
    expect(works).toContain('font-family: var(--font-editorial)')
    expect(works).toContain('font-family: var(--font-technical)')
    expect(works).toContain('max-width: var(--w-editorial)')
    expect(works).toContain('max-width: var(--w-data)')
  })

  it('preserves reduced-motion handling in the public stylesheet contract', () => {
    expect(theme).toContain('@media (prefers-reduced-motion: reduce)')
    expect(responsive).toContain('@media (prefers-reduced-motion: reduce)')
  })
})
